// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type RefreshToken struct {
	ID         int64
	UserID     uuid.UUID
	TokenHash  []byte
	CreatedAt  time.Time
	LastUsedAt sql.NullTime
	ExpiresAt  time.Time
	RevokedAt  sql.NullTime
	UserAgent  sql.NullString
	Ip         pqtype.Inet
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	Username       string
	HashedPassword string
}
