// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, created_at, last_used_at, expires_at, revoked_at, user_agent, ip
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	UserAgent sql.NullString
	Ip        pqtype.Inet
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const getActiveRefreshTokenByTokenHash = `-- name: GetActiveRefreshTokenByTokenHash :one
SELECT id, user_id, token_hash, created_at, last_used_at, expires_at, revoked_at, user_agent, ip FROM refresh_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND now() < expires_at
LIMIT 1
`

func (q *Queries) GetActiveRefreshTokenByTokenHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getActiveRefreshTokenByTokenHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const getUserFromRefreshTokenHash = `-- name: GetUserFromRefreshTokenHash :one
SELECT u.id, u.created_at, u.updated_at, u.email, u.username, u.hashed_password
FROM refresh_tokens rt
JOIN users u ON u.id = rt.user_id
WHERE rt.token_hash = $1
  AND rt.revoked_at IS NULL
  AND now() < rt.expires_at
LIMIT 1
`

func (q *Queries) GetUserFromRefreshTokenHash(ctx context.Context, tokenHash []byte) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromRefreshTokenHash, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Username,
		&i.HashedPassword,
	)
	return i, err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllRefreshTokensForUser, userID)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokenByHash, tokenHash)
	return err
}

const revokeRefreshTokenByID = `-- name: RevokeRefreshTokenByID :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokenByID, id)
	return err
}
